# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v4

      # 2. Setup do Node.js (versão consistente)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4. Debug opcional — valida a existência da chave
      - name: Verificar variável de ambiente (Google Maps Key)
        run: |
          if [[ -z "$REACT_APP_GOOGLE_MAPS_API_KEY" ]]; then
            echo "::error ::A variável REACT_APP_GOOGLE_MAPS_API_KEY está vazia ou ausente!"
            exit 1
          else
            echo "✅ Variável REACT_APP_GOOGLE_MAPS_API_KEY está presente (tamanho: ${#REACT_APP_GOOGLE_MAPS_API_KEY} caracteres)."
          fi
        env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

      # 5. Build do React App (aqui as variáveis precisam estar corretamente injetadas)
      - name: Build React app
        run: npm run build
        env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
          REACT_APP_ABACATEPAY_TOKEN: ${{ secrets.REACT_APP_ABACATEPAY_TOKEN }}

      # 6. Deploy para o Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOAFACIL_AB7E4 }}
          channelId: live
          projectId: doafacil-ab7e4
